[phases.setup]
nixPkgs = ["python311Full", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["python3 -m venv /app/venv", "/app/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "bash -c 'source /app/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT'"
# retry
